/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaPrincipal;

import ClasesFlexCup.Elementos;
import static ClasesFlexCup.Elementos.*;
import Controladores.LexicoController;
import Controladores.Paginacion;
import ProgramaPrincipal.Inicio;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduar
 */
public class Lexico extends javax.swing.JFrame {

    /**
     * Creates new form Lexico
     */
    static DefaultTableModel modeloLista;
    public static ArrayList<String> cadena = new ArrayList<String>();
    public static ArrayList<String[]> tabla = new ArrayList<String[]>();
    public static ArrayList<String> simbolos = new ArrayList<String>();//Aquí guardamos todos los simbolos validos y no repetidos nos ayudammos de atabla
    public static String[][] tablaSimbolos;
    public static int filas=0,columnas=0;
    public static String data,simbolo,tipo,valor,code,etiqueta;
    public static int cont = 0;
    public Lexico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnalisisLexicco = new javax.swing.JTextArea();
        btnLexAtras = new javax.swing.JButton();
        btnLexSiguiente = new javax.swing.JButton();
        btnCerrarLex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 100, 100));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analizador Lexico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Tai Le", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(230, 230, 230));
        jPanel1.setToolTipText("");

        txtAnalisisLexicco.setEditable(false);
        txtAnalisisLexicco.setBackground(new java.awt.Color(0, 0, 0));
        txtAnalisisLexicco.setColumns(20);
        txtAnalisisLexicco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAnalisisLexicco.setForeground(new java.awt.Color(255, 255, 255));
        txtAnalisisLexicco.setRows(5);
        jScrollPane2.setViewportView(txtAnalisisLexicco);

        btnLexAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnLexAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLexAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnLexAtras.setText("Atrás");
        btnLexAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexAtrasActionPerformed(evt);
            }
        });

        btnLexSiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnLexSiguiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLexSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnLexSiguiente.setText("Siguiente");
        btnLexSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexSiguienteActionPerformed(evt);
            }
        });

        btnCerrarLex.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarLex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrarLex.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarLex.setText("C e r r a r");
        btnCerrarLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarLexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLexAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLexSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                    .addComponent(btnCerrarLex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLexAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarLex, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarLexActionPerformed
        LexicoController.ocultar();
    }//GEN-LAST:event_btnCerrarLexActionPerformed

    private void btnLexSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexSiguienteActionPerformed
        txtAnalisisLexicco.setText(Paginacion.renglonesSiguiente(cadena));
    }//GEN-LAST:event_btnLexSiguienteActionPerformed

    private void btnLexAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexAtrasActionPerformed
        txtAnalisisLexicco.setText(Paginacion.renglonesAtras(cadena));
    }//GEN-LAST:event_btnLexAtrasActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lexico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarLex;
    private javax.swing.JButton btnLexAtras;
    private javax.swing.JButton btnLexSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea txtAnalisisLexicco;
    // End of variables declaration//GEN-END:variables
}
