/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaPrincipal;

import Controladores.Paginacion;
import Controladores.SintaxController;
import static Controladores.SintaxController.resultSin;

/**
 *
 * @author eduar
 */
public class Sintactico extends javax.swing.JFrame {

    /**
     * Creates new form Lexico
     */
    public Sintactico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnalisisSintactico = new javax.swing.JTextArea();
        btnSinAtras = new javax.swing.JButton();
        btnSinSiguiente = new javax.swing.JButton();
        btnCerrarSin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 100, 100));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analizador Sintactico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Tai Le", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(230, 230, 230));
        jPanel1.setToolTipText("");

        txtAnalisisSintactico.setEditable(false);
        txtAnalisisSintactico.setBackground(new java.awt.Color(0, 0, 0));
        txtAnalisisSintactico.setColumns(20);
        txtAnalisisSintactico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAnalisisSintactico.setForeground(new java.awt.Color(255, 255, 255));
        txtAnalisisSintactico.setRows(5);
        jScrollPane2.setViewportView(txtAnalisisSintactico);

        btnSinAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnSinAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSinAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnSinAtras.setText("Atrás");
        btnSinAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinAtrasActionPerformed(evt);
            }
        });

        btnSinSiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnSinSiguiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSinSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSinSiguiente.setText("Siguiente");
        btnSinSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinSiguienteActionPerformed(evt);
            }
        });

        btnCerrarSin.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarSin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrarSin.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSin.setText("C e r r a r");
        btnCerrarSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSinAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSinSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                    .addComponent(btnCerrarSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSinAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSinSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarSin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSinActionPerformed
        SintaxController.ocultar();
    }//GEN-LAST:event_btnCerrarSinActionPerformed

    private void btnSinSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinSiguienteActionPerformed
        txtAnalisisSintactico.setText(Paginacion.renglonesSiguiente(resultSin));
    }//GEN-LAST:event_btnSinSiguienteActionPerformed

    private void btnSinAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinAtrasActionPerformed
        txtAnalisisSintactico.setText(Paginacion.renglonesAtras(resultSin));
    }//GEN-LAST:event_btnSinAtrasActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sintactico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSin;
    private javax.swing.JButton btnSinAtras;
    private javax.swing.JButton btnSinSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea txtAnalisisSintactico;
    // End of variables declaration//GEN-END:variables
}
