
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 19 14:05:32 CDT 2021
//----------------------------------------------------

package Controladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AAM = 17;
  public static final int Parentesis_c = 61;
  public static final int Simbolo = 72;
  public static final int Parentesis_a = 60;
  public static final int AL = 38;
  public static final int Linea = 2;
  public static final int Coma = 57;
  public static final int AH = 37;
  public static final int Corchete_c = 63;
  public static final int SS = 52;
  public static final int Corchete_a = 62;
  public static final int SP = 50;
  public static final int Etiqueta = 73;
  public static final int SI = 48;
  public static final int CLI = 18;
  public static final int Separadores = 64;
  public static final int EQU = 5;
  public static final int STACK = 6;
  public static final int SUB = 29;
  public static final int STOSB = 20;
  public static final int NOT = 25;
  public static final int ERROR = 74;
  public static final int Cadena = 68;
  public static final int PROC = 12;
  public static final int ConstanteHex = 71;
  public static final int MACRO = 9;
  public static final int ES = 55;
  public static final int STI = 16;
  public static final int MUL = 24;
  public static final int WORD_PTR = 15;
  public static final int LOOPNE = 34;
  public static final int IDIV = 22;
  public static final int DX = 45;
  public static final int Comilla_s = 59;
  public static final int DW = 4;
  public static final int DS = 54;
  public static final int JS = 33;
  public static final int ADD = 26;
  public static final int DIV = 23;
  public static final int DL = 47;
  public static final int Comilla_d = 58;
  public static final int DI = 49;
  public static final int ConstanteDec = 69;
  public static final int DH = 46;
  public static final int DB = 3;
  public static final int JC = 30;
  public static final int EOF = 0;
  public static final int DUP = 67;
  public static final int CX = 42;
  public static final int JNA = 32;
  public static final int CS = 53;
  public static final int CL = 44;
  public static final int Dos_puntos = 56;
  public static final int TITLE = 65;
  public static final int CH = 43;
  public static final int OR = 28;
  public static final int error = 1;
  public static final int JAE = 35;
  public static final int DATA = 7;
  public static final int RET = 19;
  public static final int JGE = 31;
  public static final int BX = 39;
  public static final int BP = 51;
  public static final int CODE = 8;
  public static final int ENDS = 11;
  public static final int BL = 41;
  public static final int ENDP = 13;
  public static final int BH = 40;
  public static final int ENDM = 10;
  public static final int SinComa = 66;
  public static final int BYTE_PTR = 14;
  public static final int ConstanteBin = 70;
  public static final int AAS = 21;
  public static final int LES = 27;
  public static final int AX = 36;
}

